// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste-correio', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste-correio', async function() {
    await driver.get("https://buscacepinter.correios.com.br/app/endereco/index.php")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.css("main")).click()
    assert(await driver.findElement(By.css("#titulo_tela > h2")).getText() == "Busca CEP")
    await driver.findElement(By.css("main")).click()
    assert(await driver.findElement(By.css(".required label")).getText() == "Digite um CEP ou um Endereço:")
    await driver.findElement(By.id("endereco")).click()
    await driver.findElement(By.id("endereco")).sendKeys("rua dorian pontes de paula")
    await driver.findElement(By.id("btn_pesquisar")).click()
    await driver.close()
  })
})
